{% set name = "esprima-python" %}
{% set pypi_name = "esprima" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 08db1a876d3c2910db9cfaeb83108193af5411fc3a3a66ebefacd390d21323ee

build:
  noarch: python
  number: 2002
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - esprima = esprima.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - esprima

about:
  home: https://github.com/Kronuz/esprima-python
  license: BSD 2-Clause "Simplified"
  license_family: BSD
  license_file: LICENSE
  summary: 'ECMAScript parsing infrastructure for multipurpose analysis'
  description: |
    Esprima (esprima.org, BSD license) is a high performance,
    standard-compliant ECMAScript parser officially written in
    ECMAScript (also popularly known as JavaScript) and ported to
    Python. Esprima is created and maintained by Ariya Hidayat,
    with the help of many contributors.
  doc_url: http://esprima.org/doc/
  dev_url: https://github.com/Kronuz/esprima-python

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
